-- Data Analyst Internship
-- Task 3: SQL Basics – Filtering, Sorting & Aggregations
-- Dataset: MoviesDB
-- Author: Arao Zau Macaia

-- Q1: Number of movies produced by each industry
SELECT 
    industry,
    COUNT(*) AS total_movies
FROM movies
GROUP BY industry
ORDER BY total_movies DESC;

-- Q2: Average IMDb rating per industry
SELECT 
    industry,
    AVG(imdb_rating) AS avg_rating
FROM movies
WHERE imdb_rating IS NOT NULL
GROUP BY industry
ORDER BY avg_rating DESC;

-- Q3: Top 10 movies by total revenue
SELECT 
    m.title,
    f.revenue
FROM movies m
JOIN financials f 
    ON m.movie_id = f.movie_id
ORDER BY f.revenue DESC
LIMIT 10;

-- Q4: Total revenue generated by each industry
SELECT 
    m.industry,
    SUM(f.revenue) AS total_revenue
FROM movies m
JOIN financials f 
    ON m.movie_id = f.movie_id
GROUP BY m.industry
ORDER BY total_revenue DESC;

-- Q5: Most profitable movies (Revenue - Budget)
SELECT 
    m.title,
    (f.revenue - f.budget) AS profit
FROM movies m
JOIN financials f 
    ON m.movie_id = f.movie_id
ORDER BY profit DESC;

-- Q6: Budget vs revenue for movies
SELECT 
    m.title,
    f.budget,
    f.revenue
FROM movies m
JOIN financials f 
    ON m.movie_id = f.movie_id
ORDER BY f.budget DESC;

-- Q7: Actors appearing most frequently in high-rated movies (IMDb >= 8)
SELECT 
    a.name,
    COUNT(*) AS high_rated_movies
FROM actors a
JOIN movie_actor ma 
    ON a.actor_id = ma.actor_id
JOIN movies m 
    ON ma.movie_id = m.movie_id
WHERE m.imdb_rating >= 8
GROUP BY a.name
ORDER BY high_rated_movies DESC;

-- Q8: Actors associated with highest total movie revenue
SELECT 
    a.name, SUM(f.revenue) AS total_revenue
FROM
    actors a
        JOIN
    movie_actor ma ON a.actor_id = ma.actor_id
        JOIN
    movies m ON ma.movie_id = m.movie_id
        JOIN
    financials f ON m.movie_id = f.movie_id
GROUP BY a.name
ORDER BY total_revenue DESC;

-- Q9: Total revenue generated by each language
SELECT 
    l.name AS language,
    SUM(f.revenue) AS total_revenue
FROM languages l
JOIN movies m 
    ON l.language_id = m.language_id
JOIN financials f 
    ON m.movie_id = f.movie_id
GROUP BY l.name
ORDER BY total_revenue DESC;

-- Q10: Number of movies released per year
SELECT 
    release_year,
    COUNT(*) AS total_movies
FROM movies
GROUP BY release_year
ORDER BY release_year;

